### ISSUE TITLE
replce inheritance and virtuals with templates and inlines 

### ISSUE THREAD

**Issue by zkoza** [brandonpelfrey/Fast-BVH#12]
Hi, 
I  played with your code a bit. I did as follows:

- BVH was turned into a template with `Object` as its argument
- The whole  implementation of BVH was  moved to the header and marked `inline`   
- Everything but `BBox::intersect` was moved from `BBOX.cpp` to `BBox.h` and inlined
- `Sphere` no longer inherits `Object`; actually `Object.h` can be deleted
- Consequently, there are no virtual functions
- In `main.cpp` objects are defined as `vector<Sphere*> objects;`, and the definition of the bvh tree was untouched, `BVH bvh(&objects);` thanks to the new syntax of C++17 of template initialization. This makes porting the changes in  the library interface to users' code quite simple and limited in scope.  

Result: the time taken by your example program dropped from approx 780 to approx 480 ms.

**Comment by brandonpelfrey** [comment]
Very cool. Would be nice to see a PR. Do you think using link-time optimization / whole-program optimization would get the same effect?

**Comment by ghost** [comment]
@brandonpelfrey I was able to achieve this in my branch, at https://github.com/tay10r/Fast-BVH/tree/sse-removal doing a similar set of changes. It reduced the runtime of the example from 870 milliseconds to 250 milliseconds.

It's part of a branch that has also removed SSE from the code base, so those results don't even explicitly use intrinsics. I plan on submitting this as a PR as soon as I finish polishing it up.

**Edit:** This has been completed. PR has been updated.

To answer your question about whole program optimization: Probably in the example but not in projects that use complex geometry and multiple geometries.

If more than one type of primitive is added using the `Object` class interface, then users might be tempted to mix geometry. This would cause less of the executable code and data to be cached, because very different functions would be called depending on which derived class gets resolved.

Then there's the problem of complex geometry, such as hair or indexed polygonal meshes. This has more to do with the `Object` interface and not the fact that it's an abstract class and not a template. Storing triangle or polygonal surface data for an indexed mesh in an `Object` instance would require storing a copy of the indices and a pointer to the mesh data. Perhaps, at the very least, it would require a pointer to the mesh and the index of the face. For every single face in a large mesh, this would require a lot of copied data (probably 12 to 16 bytes per face.)

In the PR I made, this issue is addressed with the `Intersector` concept and `BoxConverter` concept. They aren't actual C++20 concepts, because C++20 is still a while away in terms of its support. But they will be at some point. If you wanted to get all the benefits of these concepts without using templates, you can write them as classes.

```cxx
class Intersector {
public:
  virtual ~Intersector() {}
  virtual IntersectionInfo intersect(const Object* object, const Ray& ray) = 0;
};

/* This could probably be left as object->getBBox(), but the class allows for a consistent idiom.  */
class BoxConverter {
public:
  virtual ~BoxConverter() {}
  virtual BBox getBBox(const Object* object) = 0;
}; 
```

The problem here is that, at least in the `Intersector` class, you'd have to cast `Object` to its derived class and hope that all objects have the same derived type. This is the second advantage templates have over virtual classes (in this case.)
