### ISSUE TITLE
I rendered an image of 20000^2 and found that errors are everywhere.

### ISSUE THREAD

**Issue by YukinoHayakawa** [brandonpelfrey/Fast-BVH#3]
![image](https://cloud.githubusercontent.com/assets/968003/5786619/28c2cea8-9e23-11e4-9442-25370c375169.jpg)
As you can see, some balls are clipped while some intersections between balls seem not correct.
In my experience these might be precision errors or caused by a corrupted acceleration structure.
In order to exclude the first, I scaled the balls by 100 and rendered it again. Then I got this....
![image](https://cloud.githubusercontent.com/assets/968003/5786603/da4bccca-9e22-11e4-8363-6fd76563c912.png)
Undoubtedly, there MUST be something wrong with the BVH. It might be either the structure or the algorithm.
For the code, I just modified rand01(), randVector3() and set radius of Sphere to 1.0f then put the camera at 100.0^3. I don't think these should be ruinous.

**Comment by TomCrypto** [comment]
This is because the code has a small but fatal bug in the traversal algorithm. I had in fact found (and solved) this bug over two years ago after contacting the author (Brandon) but failed to follow up with a pull request. I was kind of a git noob at the time, but now is as good a time as any to make up for that.

**Comment by brandonpelfrey** [comment]
Thanks both for reaching out to me for this long-standing bug. Glad to have this fixed.
